backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: domino14/liwords-static
  base_url: https://blog.woogles.io
  auth_endpoint: /api/auth
  auth_scope: public_repo

# publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
logo_url: https://woogles.io/static/media/woogles.c1e5d17fb6f5e90ff515.png 

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors Woogles IDs", name: "authors", widget: "list"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors Woogles IDs", name: "authors", widget: "list"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "guides" # Used in routes, e.g., /admin/collections/blog
    label: "Guide" # Used in the UI
    folder: "content/guides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors Woogles IDs", name: "authors", widget: "list"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
            
  # files
  # - label: "Pages"
  #   name: "pages"
  #   files:
  #     - label: "About Page"
  #       name: "about"
  #       file: "content/about.md"
